// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: history.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	History_HistoryList_FullMethodName   = "/history.History/HistoryList"
	History_HistoryDelete_FullMethodName = "/history.History/HistoryDelete"
	History_HistoryAsk_FullMethodName    = "/history.History/HistoryAsk"
)

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryClient interface {
	// HistoryList 智慧医生历史列表
	HistoryList(ctx context.Context, in *HistoryListRequest, opts ...grpc.CallOption) (*HistoryListResponse, error)
	// HistoryDelete 智慧医生历史删除
	HistoryDelete(ctx context.Context, in *HistoryDeleteRequest, opts ...grpc.CallOption) (*HistoryDeleteResponse, error)
	// HistoryAsk智慧医生提问
	HistoryAsk(ctx context.Context, in *HistoryAskRequest, opts ...grpc.CallOption) (*HistoryAskResponse, error)
}

type historyClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryClient(cc grpc.ClientConnInterface) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) HistoryList(ctx context.Context, in *HistoryListRequest, opts ...grpc.CallOption) (*HistoryListResponse, error) {
	out := new(HistoryListResponse)
	err := c.cc.Invoke(ctx, History_HistoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) HistoryDelete(ctx context.Context, in *HistoryDeleteRequest, opts ...grpc.CallOption) (*HistoryDeleteResponse, error) {
	out := new(HistoryDeleteResponse)
	err := c.cc.Invoke(ctx, History_HistoryDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) HistoryAsk(ctx context.Context, in *HistoryAskRequest, opts ...grpc.CallOption) (*HistoryAskResponse, error) {
	out := new(HistoryAskResponse)
	err := c.cc.Invoke(ctx, History_HistoryAsk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
// All implementations must embed UnimplementedHistoryServer
// for forward compatibility
type HistoryServer interface {
	// HistoryList 智慧医生历史列表
	HistoryList(context.Context, *HistoryListRequest) (*HistoryListResponse, error)
	// HistoryDelete 智慧医生历史删除
	HistoryDelete(context.Context, *HistoryDeleteRequest) (*HistoryDeleteResponse, error)
	// HistoryAsk智慧医生提问
	HistoryAsk(context.Context, *HistoryAskRequest) (*HistoryAskResponse, error)
	mustEmbedUnimplementedHistoryServer()
}

// UnimplementedHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (UnimplementedHistoryServer) HistoryList(context.Context, *HistoryListRequest) (*HistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryList not implemented")
}
func (UnimplementedHistoryServer) HistoryDelete(context.Context, *HistoryDeleteRequest) (*HistoryDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryDelete not implemented")
}
func (UnimplementedHistoryServer) HistoryAsk(context.Context, *HistoryAskRequest) (*HistoryAskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryAsk not implemented")
}
func (UnimplementedHistoryServer) mustEmbedUnimplementedHistoryServer() {}

// UnsafeHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServer will
// result in compilation errors.
type UnsafeHistoryServer interface {
	mustEmbedUnimplementedHistoryServer()
}

func RegisterHistoryServer(s grpc.ServiceRegistrar, srv HistoryServer) {
	s.RegisterService(&History_ServiceDesc, srv)
}

func _History_HistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).HistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_HistoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).HistoryList(ctx, req.(*HistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_HistoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).HistoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_HistoryDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).HistoryDelete(ctx, req.(*HistoryDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_HistoryAsk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryAskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).HistoryAsk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_HistoryAsk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).HistoryAsk(ctx, req.(*HistoryAskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// History_ServiceDesc is the grpc.ServiceDesc for History service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var History_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "history.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HistoryList",
			Handler:    _History_HistoryList_Handler,
		},
		{
			MethodName: "HistoryDelete",
			Handler:    _History_HistoryDelete_Handler,
		},
		{
			MethodName: "HistoryAsk",
			Handler:    _History_HistoryAsk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
